version: "3.9"

services:
  pg_db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=tg_db
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5459:5432"

volumes:
  db: